### ISSUE TITLE
where is download esp8266wifi.h ?

### ISSUE THREAD

**Issue by njlinjie** [dancol90/ESP8266Ping#10]
where is download ping.h ? thanks!

**Comment by dancol90** [comment]
Hi!
Your question is not clear, but if you want to download the library, use this link:
https://github.com/dancol90/ESP8266Ping/archive/master.zip

**Comment by njlinjie** [comment]
Thank You,In your code ESP8266Ping.h

extern "C" {
  #include <ping.h>
}
can you send me this file ,my email njlinjie@163.com

**Comment by dancol90** [comment]
That header file is part of the Espressif SDK and it is included in the ESP8266 Arduino core (https://github.com/esp8266/Arduino).
There's no need to download it elsewhere.
If your compiler doesn't find it, you're using this library wrong or your Arduino installation is not working as it should.

**Comment by njlinjie** [comment]
Thank you ,I see , My compiler is arduino-1.8.1-windows

**Comment by RASHID-AMIN** [comment]
i want esp8266wifi.h library
