### ISSUE TITLE
unable to use "Ping.ping" method, doesn't compile.

### ISSUE THREAD

**Issue by kantorv** [dancol90/ESP8266Ping#16]
any suggestions? the output of compilation error:

```sketch/SimplePing.ino.cpp.o: In function `PingClass::_ping_recv_cb(void*, void*)':```
```/home/user/Arduino/libraries/ESP8266Ping-master/src/ESP8266Ping.impl.h:65: undefined reference to `ping_start'```
```sketch/SimplePing.ino.cpp.o: In function `PingClass::ping(IPAddress, unsigned char)':```
```/home/user/Arduino/libraries/ESP8266Ping-master/src/ESP8266Ping.impl.h:65: undefined reference to `ping_start'```
```collect2: error: ld returned 1 exit status```
```exit status 1```
```Error compiling for board Generic ESP8266 Module.```

**Comment by AndreyShamis** [comment]
Check that you dont have #include <ping.h> in your skatch
Remove it or wrap it this way
`
extern "C" {
  #include <ping.h>
}
`

**Comment by kantorv** [comment]
@AndreyShamis I used `SimplePing.ino` sketch from examples folder, without modifications.

**Comment by AndreyShamis** [comment]
@kantorv Can you provide full log?

**Comment by dancol90** [comment]
Hi!

Have you updated the library to the latest version?
Which esp8266 arduino core are you using?

**Comment by kantorv** [comment]
@dancol90 , @AndreyShamis  the issue resolved after updating `esp8266 arduino core` .. 
Thank you.
