### ISSUE TITLE
DEBUG_PING

### ISSUE THREAD

**Issue by carlosrodriguesIT** [dancol90/ESP8266Ping#2]
Hello,

How can i see the values of the DEBUG_PING(), like tresp_time and ttotal_time?

Thanks in advance

**Comment by dancol90** [comment]
Hi!

Update to the last commit and define ENABLE_DEBUG_PING before including the library in your sketch, like this:

``` C++
#define ENABLE_DEBUG_PING
#include <ESP8266Ping.h>
```

**Comment by carlosrodriguesIT** [comment]
OK, but how to call in the main file? And display the values?

**Comment by dancol90** [comment]
It's a debug statement, so it will be called during the execution of `Ping.ping()`. When enabled, the informations will be printed on Serial.

At the moment, there's no other way to access `ping_resp` structure from outside the library. The only information available is the average response time, using `Ping.averageTime()`.

**Comment by carlosrodriguesIT** [comment]
Yes I see, maybe construct other class like `PingValuesClass PingValues;` to show the other values, what do you think?

**Comment by dancol90** [comment]
I will think about implementing a user-defined callback that gets called on every response, that will pass a reference to the `ping_resp` structure.

**Comment by carlosrodriguesIT** [comment]
Yes , the people would love , would be much more complete!

I will wait for this implementation, thanks a lot for your time (Y)

**Comment by dancol90** [comment]
I've realised that the define method above does not work, I'm sorry!
In #4 I've suggested a workaround to make the debug prints works.

**Comment by dancol90** [comment]
Debug info print issue fixed by c5f0be4
