### ISSUE TITLE
Average Time, Debug Infos ?

### ISSUE THREAD

**Issue by Greece2** [dancol90/ESP8266Ping#25]
How can one enable the debug function 
of this lib
`ENABLE_DEBUG_PING` 
without having to make changes to the lib itself ?
How can one print aditional info like number of errors, average time etc. ?
Nothing about that in the Demos.

Thanks !  I'm a newby, so excuse my questions ;-)

**Comment by dancol90** [comment]
Hi! Just add the define before including the library in your sketch:

```c++
#define ENABLE_DEBUG_PING
#include <ESP8266Ping.h>
```

**Comment by Greece2** [comment]
Hi!  I'll give that a try, thanks !
I found out that
`    int avg_time_ms = Ping.averageTime();
    Serial.print("Av.Time: ");
    Serial.println(avg_time_ms);`
prints the average repsonse time :-)
