### ISSUE TITLE
Please make ping async

### ISSUE THREAD

**Issue by sblantipodi** [dancol90/ESP8266Ping#31]
As title,
pinging requires a lot of time with this lib.

Is it possible to make it async?

**Comment by skorokithakis** [comment]
Seconded, I want to do some work while the library is pinging and right now it's not possible.

**Comment by maiksicks** [comment]
@sblantipodi You could call `Ping.ping(host, 1);` to only send one ping request. This works quite fast.

**Comment by sblantipodi** [comment]
> @sblantipodi You could call `Ping.ping(host, 1);` to only send one ping request. This works quite fast.

I'm running a stepper motor, this cause huge rattle

**Comment by ziqbal** [comment]
@skorokithakis @sblantipodi
You all probably figured it out but I had this same issue past week and resolved it by using another library: [AsyncPing](https://github.com/akaJes/AsyncPing
)
It works a treat.

**Comment by skorokithakis** [comment]
@ziqbal  Hey Zafar! Long time! Thanks for the tip, I'll use that.

**Comment by sblantipodi** [comment]
@maiksicks it's fast but if you are driving a stepper motor on a single core microcontroller it creates a rattle every time you do a ping. :) Not an enormous issues but an async call could be cool.

**Comment by sblantipodi** [comment]
@dancol90 wow you close this issue, can I ask you how to "make it async"?
should I change somethig in my code?

is the 
`bool ret = Ping.ping("www.google.com");`
now async?

**Comment by maiksicks** [comment]
@sblantipodi What about this? :)
#47
