### ISSUE TITLE
'INT_MAX' was not declared in this scope

### ISSUE THREAD

**Issue by samtrot** [dancol90/ESP8266Ping#33]
```
ESP8266Ping-master\src/ESP8266Ping.impl.h:30:17: error: 'INT_MAX' was not declared in this scope
     _min_time = INT_MAX;
                 ^
exit status 1
```

Hello,

I tried to use the library, but got above error. Do I have to declare INT_MAX myself?

Best Regards

**Comment by dancol90** [comment]
You're missing some includes, or probably not using the right Arduino core.
